### PR TITLE
Add uploadExtraArgs support

### LINKED ISSUE #94: Custom headers?
Is there a way to invoke lighthouse with custom headers? The lighthouse docs say you can do this via a CLI flag: https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md#option-3-pass-custom-request-headers-with-lighthouse-cli, but I don't see a way to pass raw Lighthouse CLI flags. I have sensitive authorization headers stored in GitHub Secrets that I don't want to add to a file on a file system (or worse, source control).

### PR DESCRIPTION
**Pull request by Djiit**
Hi there :wave:, 

Trying to add support for extraArgs for the upload command, mostly to be able to pass extraHeaders (but can be arbitrary args).

Any guidance are appreciated, I might have missed something.

I'm also OK to refactor this and focus on uploadExtraHeaders (a less generic version) if it makes more sense.

Cheers

Fixes #94

### CODE REVIEW

**Comment by Djiit** [comment]
Hey @alekseykulikov , any chance to have this reviewed or merged anytime soon ? Thanks 🙏

**Comment by alekseykulikov** [comment]
Hi @Djiit ! Could you clarify your case, why do you need custom argument?
The action supports `serverBaseUrl` & `serverToken` to upload to LHCI Server.

**Comment by Djiit** [comment]
Hey, thanks for your answer. In my case, my server sits behind cloudflare and I need to pass an arbitrary header to reach it.

**Comment by Djiit** [comment]
@alekseykulikov any news? Thanks 🙏

**Comment by Djiit** [comment]
Hey @alekseykulikov do you think we can merge this ?

**Comment by alekseykulikov** [comment]
Hey, we could, but I'm unsure about the balance of extra complexity vs. usefulness. 
Let's keep the issue open and see if more people need it.

**Comment by diimpp** [comment]
I would like to execute upload with `--githubStatusContextSuffix` to able to able to different between multiple runs (mobile, desktop)

```js
      await exec.exec('lhci', ['upload', '--githubStatusContextSuffix', '/mobile']);
```

https://github.com/GoogleChrome/lighthouse-ci/issues/138#issuecomment-1196379684

**Comment by tanguyantoine** [comment]
It would be very helpfull

**Pull request merged**
